name: Python Example

on: push # pull, page_build, pull/push(branches: master), schedule(Cron job), manual

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ['3.x', 'pypy-3.6', 'pypy-3.7']
    name: Python script #${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2 # setup this repo on workflow
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.7 #${{ matrix.python-version }}
          # architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install black
          pip install pytest
          pip install -U scikit-learn
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Run linter
      #   run: black --check .

      - name: Test with pytest
        run: |
          pytest .
      - run: python script.py
