name: Python Example

on: push # pull, page_build, pull/push(branches: master), schedule(Cron job), manual

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ['3.x', 'pypy-3.6', 'pypy-3.7']
    name: Python script #${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2 # setup this repo on workflow
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.7 #${{ matrix.python-version }}
          # architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install black
          pip install pytest
          pip install -U scikit-learn
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest test.py
      - name: Run Script
        run: python script.py
      # - name: Format Code
      #   run: black script.py
      - name: black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: .
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name $MY_USERNAME
          git config --global user.email $MY_EMAIL
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "Automated changes"
          git push
